#!/usr/bin/env python3
from pathlib import Path
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else 'build/PrePoMax-CodeAster')
path = root / 'PrePoMax' / 'AsterMaxAI' / 'AsterMaxStepMeshHarness.cs'
text = path.read_text(encoding='utf-8-sig')
anchor = '''                meshedPartName = geometry.Parts.First().Key;\n                // Pinned native path: Controller.CreateMesh -> CreateMeshFromBrep -> NetGenMesher -> ImportGeneratedMesh.\n                createMeshReturned = _controller.CreateMesh(meshedPartName);'''
replacement = '''                meshedPartName = geometry.Parts.First().Key;\n\n                // C8.82: optional, explicit native NetGen mesh-size contract for sensitivity studies.\n                // MaxH is expressed in the model length unit; this harness already qualifies the STEP as SI millimetres.\n                string maxHText = Environment.GetEnvironmentVariable("ASTERMAX_STEP_MESH_MAXH_MM");\n                if (!String.IsNullOrWhiteSpace(maxHText))\n                {\n                    double requestedMaxH;\n                    if (!Double.TryParse(maxHText, NumberStyles.Float, CultureInfo.InvariantCulture, out requestedMaxH) ||\n                        !Finite(requestedMaxH) || requestedMaxH <= 0)\n                        throw new InvalidOperationException("ASTERMAX_STEP_MESH_MAXH_MM must be a finite value > 0 mm.");\n                    MeshingParameters p = _controller.Settings.Meshing.MeshingParameters;\n                    p.RelativeSize = false;\n                    p.MaxH = requestedMaxH;\n                    p.MinH = 0;\n                    p.SecondOrder = true;\n                    string cfgPath = Environment.GetEnvironmentVariable("ASTERMAX_STEP_MESH_CONFIG_EVIDENCE_PATH");\n                    if (!String.IsNullOrWhiteSpace(cfgPath))\n                    {\n                        string cfgDir = Path.GetDirectoryName(cfgPath);\n                        if (!String.IsNullOrWhiteSpace(cfgDir)) Directory.CreateDirectory(cfgDir);\n                        File.WriteAllText(cfgPath, "{\\n  \\\"schema\\\": \\\"astermax.c8.82.native-netgen-size.v1\\\",\\n  \\\"requested_maxh_mm\\\": " +\n                            requestedMaxH.ToString("R", CultureInfo.InvariantCulture) +\n                            ",\\n  \\\"relative_size\\\": false,\\n  \\\"second_order_requested\\\": true,\\n  \\\"industrial_validation\\\": false,\\n  \\\"ansys_equivalence\\\": false\\n}", Encoding.UTF8);\n                    }\n                }\n\n                // Pinned native path: Controller.CreateMesh -> CreateMeshFromBrep -> NetGenMesher -> ImportGeneratedMesh.\n                createMeshReturned = _controller.CreateMesh(meshedPartName);'''
if anchor not in text:
    raise SystemExit('C8.82 mesh-size anchor not found; refusing non-deterministic patch')
text = text.replace(anchor, replacement, 1)
path.write_text(text, encoding='utf-8')
print(f'C8.82 native NetGen mesh-size seam applied: {path}')
