from __future__ import annotations

import hashlib
import json
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field, model_validator


class MeshSizingV1(BaseModel):
    model_config = ConfigDict(extra="forbid")

    global_size_mm: float = Field(gt=0)
    interface_size_mm: float = Field(gt=0)
    interface_refine_distance_mm: float = Field(gt=0)
    element_order: int = Field(default=2, ge=1, le=2)

    @model_validator(mode="after")
    def validate_sizes(self) -> "MeshSizingV1":
        if self.interface_size_mm > self.global_size_mm:
            raise ValueError("interface mesh size cannot exceed global mesh size")
        return self


class PrivateStepMeshRequestV1(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: str = Field(
        default="PrivateStepMeshRequestV1", pattern=r"^PrivateStepMeshRequestV1$"
    )
    step_path: str = Field(min_length=1)
    step_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    coordinate_unit: str = Field(default="mm", pattern=r"^mm$")
    expected_solid_count: int = Field(default=6, ge=2)
    expected_segment_count: int = Field(default=5, ge=1)
    interface_plane_x_mm: float
    interface_plane_tolerance_mm: float = Field(default=1e-4, gt=0)
    segment_volume_relative_tolerance: float = Field(default=1e-6, gt=0)
    sizing: MeshSizingV1
    exploratory_result_class: str = Field(
        default="EXPLORATORY_NOT_FOR_ACCEPTANCE",
        pattern=r"^EXPLORATORY_NOT_FOR_ACCEPTANCE$",
    )


class GeneratedMeshingPackV1(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: str = Field(
        default="GeneratedMeshingPackV1", pattern=r"^GeneratedMeshingPackV1$"
    )
    request_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    source_step_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    gmsh_script_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    output_mesh_name: str
    exploratory_result_class: str = "EXPLORATORY_NOT_FOR_ACCEPTANCE"
    authentic_solver_authorized: bool = False
    instructions: list[str]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def canonical_request_sha256(request: PrivateStepMeshRequestV1) -> str:
    payload = request.model_dump_json(exclude_none=True)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def validate_private_step(request: PrivateStepMeshRequestV1) -> Path:
    path = Path(request.step_path).expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(path)
    actual = sha256_file(path)
    if actual != request.step_sha256:
        raise ValueError(
            f"STEP SHA-256 mismatch: expected {request.step_sha256}, got {actual}"
        )
    return path


def render_gmsh_python_job(
    request: PrivateStepMeshRequestV1,
    *,
    output_mesh_name: str = "astermax_exploratory.med",
) -> str:
    """Render a self-contained Gmsh Python job.

    The generated job is intentionally private-input oriented: it imports the STEP at
    runtime, classifies the unique largest solid as the hub, verifies five near-equal
    remaining segment volumes, finds posterior planar surfaces by bounding-box X
    location, refines near that authenticated interface and writes MED. It performs no
    topology healing, boolean fusion or geometry scaling.
    """

    cfg = request.model_dump()
    cfg_json = json.dumps(cfg, sort_keys=True)
    return f'''# Generated by AsterMax W2I. EXPLORATORY_NOT_FOR_ACCEPTANCE.
import hashlib
import json
from pathlib import Path
import gmsh

CFG = json.loads({cfg_json!r})
OUTPUT_MESH = {output_mesh_name!r}


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


step_path = Path(CFG["step_path"]).expanduser().resolve()
if not step_path.is_file():
    raise SystemExit(f"STEP not found: {{step_path}}")
actual_sha = sha256_file(step_path)
if actual_sha != CFG["step_sha256"]:
    raise SystemExit(f"STEP SHA mismatch: expected {{CFG['step_sha256']}}, got {{actual_sha}}")

gmsh.initialize()
try:
    gmsh.option.setNumber("General.Terminal", 1)
    gmsh.model.add("astermax_private_step")
    gmsh.merge(str(step_path))
    gmsh.model.occ.synchronize()

    volumes = [tag for dim, tag in gmsh.model.getEntities(3)]
    if len(volumes) != CFG["expected_solid_count"]:
        raise RuntimeError(
            f"solid count mismatch: expected {{CFG['expected_solid_count']}}, got {{len(volumes)}}"
        )

    volume_mass = {{tag: gmsh.model.occ.getMass(3, tag) for tag in volumes}}
    hub = max(volumes, key=lambda tag: volume_mass[tag])
    segments = [tag for tag in volumes if tag != hub]
    if len(segments) != CFG["expected_segment_count"]:
        raise RuntimeError("segment count mismatch after largest-volume hub classification")

    segment_masses = [volume_mass[tag] for tag in segments]
    segment_nominal = sum(segment_masses) / len(segment_masses)
    rel_tol = CFG["segment_volume_relative_tolerance"]
    for tag in segments:
        rel = abs(volume_mass[tag] - segment_nominal) / segment_nominal
        if rel > rel_tol:
            raise RuntimeError(
                f"segment volume signature mismatch for volume {{tag}}: relative deviation={{rel}}"
            )

    gmsh.model.addPhysicalGroup(3, [hub], name="HUB")
    gmsh.model.addPhysicalGroup(3, segments, name="SEGMENTS")
    for idx, tag in enumerate(sorted(segments), start=1):
        gmsh.model.addPhysicalGroup(3, [tag], name=f"SEGMENT_{{idx:02d}}")

    target_x = CFG["interface_plane_x_mm"]
    tol = CFG["interface_plane_tolerance_mm"]

    def posterior_surfaces(volume_tag):
        result = []
        boundary = gmsh.model.getBoundary([(3, volume_tag)], oriented=False, recursive=False)
        for dim, surf in boundary:
            if dim != 2:
                continue
            xmin, ymin, zmin, xmax, ymax, zmax = gmsh.model.getBoundingBox(2, surf)
            if abs(xmin - target_x) <= tol and abs(xmax - target_x) <= tol:
                result.append(surf)
        return sorted(set(result))

    hub_interface = posterior_surfaces(hub)
    segment_interface = sorted({{
        surf for tag in segments for surf in posterior_surfaces(tag)
    }})
    if not hub_interface:
        raise RuntimeError("authenticated hub posterior interface plane not found")
    if len(segment_interface) < len(segments):
        raise RuntimeError("posterior segment interface selection is incomplete")

    gmsh.model.addPhysicalGroup(2, hub_interface, name="HUB_POSTERIOR_INTERFACE")
    gmsh.model.addPhysicalGroup(2, segment_interface, name="SEGMENT_POSTERIOR_INTERFACE")

    # Mesh refinement only; no healing/fusing/scaling is performed.
    distance = gmsh.model.mesh.field.add("Distance")
    gmsh.model.mesh.field.setNumbers(
        distance, "FacesList", hub_interface + segment_interface
    )
    threshold = gmsh.model.mesh.field.add("Threshold")
    gmsh.model.mesh.field.setNumber(threshold, "InField", distance)
    gmsh.model.mesh.field.setNumber(
        threshold, "SizeMin", CFG["sizing"]["interface_size_mm"]
    )
    gmsh.model.mesh.field.setNumber(
        threshold, "SizeMax", CFG["sizing"]["global_size_mm"]
    )
    gmsh.model.mesh.field.setNumber(threshold, "DistMin", 0.0)
    gmsh.model.mesh.field.setNumber(
        threshold, "DistMax", CFG["sizing"]["interface_refine_distance_mm"]
    )
    gmsh.model.mesh.field.setAsBackgroundMesh(threshold)
    gmsh.option.setNumber("Mesh.MeshSizeMax", CFG["sizing"]["global_size_mm"])
    gmsh.option.setNumber("Mesh.MeshSizeMin", CFG["sizing"]["interface_size_mm"])
    gmsh.option.setNumber("Mesh.SaveAll", 0)

    gmsh.model.mesh.generate(3)
    if CFG["sizing"]["element_order"] == 2:
        gmsh.model.mesh.setOrder(2)

    gmsh.write(OUTPUT_MESH)
    mesh_sha = sha256_file(OUTPUT_MESH)
    evidence = {{
        "schema_version": "PrivateMeshExecutionEvidenceV1",
        "result_class": "EXPLORATORY_NOT_FOR_ACCEPTANCE",
        "authentic_solver_authorized": False,
        "source_step_sha256": actual_sha,
        "mesh_sha256": mesh_sha,
        "mesh_file": OUTPUT_MESH,
        "solid_count": len(volumes),
        "hub_volume_tag": hub,
        "segment_volume_tags": sorted(segments),
        "hub_volume_mm3": volume_mass[hub],
        "segment_volumes_mm3": [volume_mass[tag] for tag in sorted(segments)],
        "hub_interface_surfaces": hub_interface,
        "segment_interface_surfaces": segment_interface,
        "gmsh_version": gmsh.option.getString("General.Version"),
        "coordinate_unit": "mm",
    }}
    with open("mesh_execution_evidence.json", "w", encoding="utf-8") as f:
        json.dump(evidence, f, indent=2, sort_keys=True)
finally:
    gmsh.finalize()
'''


def generate_private_meshing_pack(
    request: PrivateStepMeshRequestV1,
    output_dir: Path,
    *,
    output_mesh_name: str = "astermax_exploratory.med",
) -> GeneratedMeshingPackV1:
    validate_private_step(request)
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    script = render_gmsh_python_job(request, output_mesh_name=output_mesh_name)
    script_path = output_dir / "mesh_private_step.py"
    script_path.write_text(script, encoding="utf-8", newline="\n")
    script_sha = sha256_file(script_path)

    request_path = output_dir / "mesh_request.json"
    request_path.write_text(
        request.model_dump_json(indent=2), encoding="utf-8", newline="\n"
    )

    pack = GeneratedMeshingPackV1(
        request_sha256=canonical_request_sha256(request),
        source_step_sha256=request.step_sha256,
        gmsh_script_sha256=script_sha,
        output_mesh_name=output_mesh_name,
        authentic_solver_authorized=False,
        instructions=[
            "Install an approved Gmsh version on the private execution host.",
            "Run: python mesh_private_step.py",
            "Require mesh_execution_evidence.json and verify the emitted MED SHA-256.",
            "Do not commit STEP/MED/evidence containing private geometry to the public repository.",
            "Any downstream solver run remains EXPLORATORY_NOT_FOR_ACCEPTANCE until W2F becomes READY.",
        ],
    )
    (output_dir / "meshing_pack_manifest.json").write_text(
        pack.model_dump_json(indent=2), encoding="utf-8", newline="\n"
    )
    return pack
