from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import json
from pathlib import Path
import re


class CodeAsterStudyError(RuntimeError):
    pass


_GROUP_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,23}$")


@dataclass(frozen=True)
class LinearStaticStudy:
    mesh_filename: str
    support_group: str
    load_group: str
    young_mpa: float
    poisson: float
    force_n: tuple[float, float, float]
    units_length: str = "mm"
    units_force: str = "N"
    units_stress: str = "MPa"

    def validate(self) -> None:
        if self.units_length != "mm" or self.units_force != "N" or self.units_stress != "MPa":
            raise CodeAsterStudyError("CODE_ASTER_STUDY_UNITS_MUST_BE_MM_N_MPA")
        if Path(self.mesh_filename).name != self.mesh_filename or not self.mesh_filename.lower().endswith(".med"):
            raise CodeAsterStudyError("CODE_ASTER_STUDY_MESH_MUST_BE_LOCAL_MED")
        for value, label in ((self.support_group, "support"), (self.load_group, "load")):
            if not _GROUP_RE.fullmatch(value):
                raise CodeAsterStudyError(f"CODE_ASTER_STUDY_INVALID_{label.upper()}_GROUP")
        if self.support_group == self.load_group:
            raise CodeAsterStudyError("CODE_ASTER_STUDY_GROUPS_MUST_DIFFER")
        if not (self.young_mpa > 0.0):
            raise CodeAsterStudyError("CODE_ASTER_STUDY_YOUNG_MUST_BE_POSITIVE")
        if not (-1.0 < self.poisson < 0.5):
            raise CodeAsterStudyError("CODE_ASTER_STUDY_POISSON_OUT_OF_RANGE")
        if len(self.force_n) != 3 or not all(float(v) == v and abs(v) < float("inf") for v in self.force_n):
            raise CodeAsterStudyError("CODE_ASTER_STUDY_FORCE_INVALID")
        if max(abs(v) for v in self.force_n) <= 0.0:
            raise CodeAsterStudyError("CODE_ASTER_STUDY_FORCE_ZERO")


def render_linear_static_comm(study: LinearStaticStudy) -> str:
    study.validate()
    fx, fy, fz = study.force_n
    return f"""# Generated by AsterMax. Unit contract: mm / N / MPa.\nDEBUT()\n\nmesh = LIRE_MAILLAGE(FORMAT='MED', UNITE=20)\n\nmodel = AFFE_MODELE(\n    MAILLAGE=mesh,\n    AFFE=_F(TOUT='OUI', PHENOMENE='MECANIQUE', MODELISATION='3D'),\n)\n\nmaterial = DEFI_MATERIAU(ELAS=_F(E={study.young_mpa:.17g}, NU={study.poisson:.17g}))\n\nmatfield = AFFE_MATERIAU(\n    MAILLAGE=mesh,\n    AFFE=_F(TOUT='OUI', MATER=material),\n)\n\nfixed = AFFE_CHAR_MECA(\n    MODELE=model,\n    DDL_IMPO=_F(GROUP_MA='{study.support_group}', DX=0.0, DY=0.0, DZ=0.0),\n)\n\nload = AFFE_CHAR_MECA(\n    MODELE=model,\n    FORCE_FACE=_F(GROUP_MA='{study.load_group}', FX={fx:.17g}, FY={fy:.17g}, FZ={fz:.17g}),\n)\n\nresult = MECA_STATIQUE(\n    MODELE=model,\n    CHAM_MATER=matfield,\n    EXCIT=(_F(CHARGE=fixed), _F(CHARGE=load)),\n)\n\nresult = CALC_CHAMP(\n    reuse=result,\n    RESULTAT=result,\n    CONTRAINTE=('SIGM_ELNO',),\n    CRITERES=('SIEQ_ELNO',),\n)\n\nIMPR_RESU(\n    FORMAT='MED',\n    UNITE=80,\n    RESU=_F(RESULTAT=result, NOM_CHAM=('DEPL', 'SIGM_ELNO', 'SIEQ_ELNO')),
)\n\nFIN()\n"""


def study_sha256(study: LinearStaticStudy) -> str:
    study.validate()
    payload = {
        "mesh_filename": study.mesh_filename,
        "support_group": study.support_group,
        "load_group": study.load_group,
        "young_mpa": study.young_mpa,
        "poisson": study.poisson,
        "force_n": list(study.force_n),
        "units": [study.units_length, study.units_force, study.units_stress],
    }
    return sha256(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")).hexdigest()


def write_study_bundle(study: LinearStaticStudy, directory: str | Path) -> dict[str, object]:
    study.validate()
    root = Path(directory)
    root.mkdir(parents=True, exist_ok=True)
    comm = root / "astermax.comm"
    comm.write_text(render_linear_static_comm(study), encoding="utf-8", newline="\n")
    evidence = {
        "study_sha256": study_sha256(study),
        "comm_sha256": sha256(comm.read_bytes()).hexdigest(),
        "mesh_filename": study.mesh_filename,
        "support_group": study.support_group,
        "load_group": study.load_group,
        "units_length": "mm",
        "units_force": "N",
        "units_stress": "MPa",
        "fea_solve_executed": False,
        "results_verified": False,
    }
    (root / "study_evidence.json").write_text(json.dumps(evidence, indent=2, sort_keys=True), encoding="utf-8")
    return evidence
