from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import json
from pathlib import Path
import re


class CodeAsterExportError(RuntimeError):
    pass


_LOCAL_FILE_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$")


def _require_local_filename(value: str, *, suffix: str, label: str) -> str:
    if Path(value).name != value or not _LOCAL_FILE_RE.fullmatch(value):
        raise CodeAsterExportError(f"CODE_ASTER_EXPORT_INVALID_{label}_FILENAME")
    if not value.lower().endswith(suffix):
        raise CodeAsterExportError(f"CODE_ASTER_EXPORT_INVALID_{label}_SUFFIX")
    return value


def _sha256_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


@dataclass(frozen=True)
class CodeAsterExportSpec:
    command_filename: str = "astermax.comm"
    input_med_filename: str = "astermax.med"
    result_med_filename: str = "astermax_result.med"
    time_limit_s: int = 300
    memory_limit_mb: int = 2048
    ncpus: int = 1
    mpi_nbcpu: int = 1

    def validate(self) -> None:
        _require_local_filename(self.command_filename, suffix=".comm", label="COMMAND")
        _require_local_filename(self.input_med_filename, suffix=".med", label="INPUT_MED")
        _require_local_filename(self.result_med_filename, suffix=".med", label="RESULT_MED")
        if len({self.command_filename.lower(), self.input_med_filename.lower(), self.result_med_filename.lower()}) != 3:
            raise CodeAsterExportError("CODE_ASTER_EXPORT_FILENAMES_MUST_DIFFER")
        if not (1 <= self.time_limit_s <= 86400):
            raise CodeAsterExportError("CODE_ASTER_EXPORT_TIME_LIMIT_OUT_OF_RANGE")
        if not (128 <= self.memory_limit_mb <= 1048576):
            raise CodeAsterExportError("CODE_ASTER_EXPORT_MEMORY_LIMIT_OUT_OF_RANGE")
        if not (1 <= self.ncpus <= 256):
            raise CodeAsterExportError("CODE_ASTER_EXPORT_NCPUS_OUT_OF_RANGE")
        if not (1 <= self.mpi_nbcpu <= 256):
            raise CodeAsterExportError("CODE_ASTER_EXPORT_MPI_NBCPU_OUT_OF_RANGE")


def render_export(spec: CodeAsterExportSpec) -> str:
    """Render a portable run_aster .export file using only relative local paths.

    Units 1, 20 and 80 match the command file, MED input and MED result logical
    units used by AsterMax's deterministic Code_Aster study contract.
    """
    spec.validate()
    return (
        "# Generated by AsterMax. Portable relative-path Code_Aster study.\n"
        f"P time_limit {spec.time_limit_s}\n"
        f"P memory_limit {spec.memory_limit_mb}\n"
        f"P ncpus {spec.ncpus}\n"
        f"P mpi_nbcpu {spec.mpi_nbcpu}\n"
        f"F comm {spec.command_filename} D 1\n"
        f"F mmed {spec.input_med_filename} D 20\n"
        f"F rmed {spec.result_med_filename} R 80\n"
    )


def write_execution_bundle(
    directory: str | Path,
    *,
    spec: CodeAsterExportSpec | None = None,
    export_filename: str = "astermax.export",
) -> dict[str, object]:
    """Validate an existing .comm + input MED and add a portable .export.

    This function prepares executable solver inputs but does not execute
    Code_Aster and therefore never claims a completed FEA solve.
    """
    chosen = spec or CodeAsterExportSpec()
    chosen.validate()
    _require_local_filename(export_filename, suffix=".export", label="EXPORT")

    root = Path(directory).expanduser().resolve()
    if not root.is_dir():
        raise CodeAsterExportError("CODE_ASTER_BUNDLE_DIRECTORY_NOT_FOUND")

    command = root / chosen.command_filename
    input_med = root / chosen.input_med_filename
    result_med = root / chosen.result_med_filename
    for path, code in ((command, "COMMAND"), (input_med, "INPUT_MED")):
        if not path.is_file():
            raise CodeAsterExportError(f"CODE_ASTER_BUNDLE_{code}_NOT_FOUND")
        if path.stat().st_size <= 0:
            raise CodeAsterExportError(f"CODE_ASTER_BUNDLE_{code}_EMPTY")
    if result_med.exists():
        raise CodeAsterExportError("CODE_ASTER_BUNDLE_RESULT_PREEXISTS")

    export_path = root / export_filename
    export_path.write_text(render_export(chosen), encoding="utf-8", newline="\n")

    evidence = {
        "export_filename": export_filename,
        "command_filename": chosen.command_filename,
        "input_med_filename": chosen.input_med_filename,
        "result_med_filename": chosen.result_med_filename,
        "export_sha256": _sha256_file(export_path),
        "command_sha256": _sha256_file(command),
        "input_med_sha256": _sha256_file(input_med),
        "time_limit_s": chosen.time_limit_s,
        "memory_limit_mb": chosen.memory_limit_mb,
        "ncpus": chosen.ncpus,
        "mpi_nbcpu": chosen.mpi_nbcpu,
        "portable_relative_paths": True,
        "fea_solve_executed": False,
        "results_verified": False,
    }
    evidence_path = root / "execution_bundle_evidence.json"
    evidence_path.write_text(json.dumps(evidence, indent=2, sort_keys=True), encoding="utf-8")
    return evidence
